/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountSettings: typeof import('./../../components/AccountSettings.vue')['default']
    Bank: typeof import('./../../components/Bank.vue')['default']
    BankBankHeader: typeof import('./../../components/bank/BankHeader.vue')['default']
    BankBankItemDialog: typeof import('./../../components/bank/BankItemDialog.vue')['default']
    BankBankList: typeof import('./../../components/bank/BankList.vue')['default']
    ConflictResolver: typeof import('./../../components/ConflictResolver.vue')['default']
    GlobalImport: typeof import('./../../components/GlobalImport.vue')['default']
    LayoutLayoutDrawer: typeof import('./../../components/layout/LayoutDrawer.vue')['default']
    LayoutLayoutHeader: typeof import('./../../components/layout/LayoutHeader.vue')['default']
    MainChatTabs: typeof import('./../../components/main/ChatTabs.vue')['default']
    MainInput: typeof import('./../../components/main/Input.vue')['default']
    MainSpotlightDialog: typeof import('./../../components/main/SpotlightDialog.vue')['default']
    MobileAppPrompt: typeof import('./../../components/MobileAppPrompt.vue')['default']
    OfflineIndicator: typeof import('./../../components/OfflineIndicator.vue')['default']
    Predictor: typeof import('./../../components/Predictor.vue')['default']
    Quickes: typeof import('./../../components/Quickes.vue')['default']
    Reader: typeof import('./../../components/Reader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsAccountTab: typeof import('./../../components/settings/AccountTab.vue')['default']
    SettingsAdaptiveSettingsTab: typeof import('./../../components/settings/AdaptiveSettingsTab.vue')['default']
    SettingsImportTab: typeof import('./../../components/settings/ImportTab.vue')['default']
    SettingsVoiceSettingsTab: typeof import('./../../components/settings/VoiceSettingsTab.vue')['default']
    ShortcutList: typeof import('./../../components/ShortcutList.vue')['default']
    TextEditor: typeof import('./../../components/TextEditor.vue')['default']
    Tutorial: typeof import('./../../components/Tutorial.vue')['default']
    UpdatePrompt: typeof import('./../../components/UpdatePrompt.vue')['default']
  }
}
