# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
      name: Deploy
      runs-on: ubuntu-latest
      steps:

        - name: Checkout Repo
          uses: actions/checkout@master

        - name: Cache
          uses: actions/cache@v2.1.8
          with:
            # A list of files, directories, and wildcard patterns to cache and restore
            path: node_modules
            
        - name: Setup Node.js environment
          uses: actions/setup-node@v2.5.2
          with:
            # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
            node-version: 16.x
        - run: npm i
        - run: npm run build
        - name: Deploy to Firebase
          uses: w9jds/firebase-action@master
          with:
            args: deploy --only hosting
          env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        - name: Deploy functions
          uses: w9jds/firebase-action@master
          with:
            max_attempts: 5
            retry_on: error
            args: deploy --only functions
          env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}